// https://github.com/fent/chrome-options

cas_companion.options.opts.about = "<h3>CAS Companion</h3>This application adds CAS Companion to MS Teams";
cas_companion.options.opts.autoSave = true;
cas_companion.options.opts.saveDefaults = true;

cas_companion.options.addTab('Configuration', [
    { name: 'cas_enabled', desc: 'Enables CAS Service' },
    { type: 'h3', desc: 'Connection' },	
    { name: 'cas_server_url', 'default': 'http://localhost', type: 'text', desc: 'The url for CAS Service', singleline: true },
    { name: 'cas_server_token', 'default': 'cCWcsOsxprO2BhnUnondjSqBLzPk1dCFf4Bb24JE', type: 'text', desc: 'The CAS access token assigned', singleline: true },

]);

cas_companion.options.addTab('User Interface', [
    { name: 'cas_enable_dialer', desc: 'Enables CAS Dialer' },
    { name: 'cas_enable_web_apps', desc: 'Enable Web Apps for Active Calls' },	
    { name: 'cas_enable_audioonly', desc: 'Enable Audio Only Mode' },
    { name: 'cas_enable_notifications', desc: 'Enable Notification Popups' },	
    { name: 'cas_enable_tel_protocol', desc: 'Enable TEL: Protocol Handler' },	
    { name: 'cas_default_web_app', 'default': 'https://comitfs.github.io/cas-omni/demo/crm/', type: 'text', desc: 'The default Web App', singleline: true },
    { name: 'cas_telephone_contry_code', type: 'select', desc: 'Telephone Country Code', options: [
		{desc: "Algeria", value: "ar-DZ"},
		{desc: "Argentina", value: "es-AR"},
		{desc: "Australia", value: "en-AU"},
		{desc: "Bahrain", value: "ar-BH"},
		{desc: "Bolivia", value: "es-BO"},
		{desc: "Brazil", value: "pt-BR"},
		{desc: "Bulgaria", value: "bg-BG"},
		{desc: "Canada", value: "en-CA"},
		{desc: "Chile", value: "es-CL"},
		{desc: "China (Simp.)", value: "cmn-Hans-CN"},
		{desc: "Colombia", value: "es-CO"},
		{desc: "Costa Rica", value: "es-CR"},
		{desc: "Croatia", value: "hr_HR"},
		{desc: "Czech Republic", value: "cs-CZ"},
		{desc: "Denmark", value: "da-DK"},
		{desc: "Dominican Republic", value: "es-DO"},
		{desc: "Ecuador", value: "es-EC"},
		{desc: "Egypt", value: "ar-EG"},
		{desc: "El Salvador", value: "es-SV"},
		{desc: "Finland", value: "fi-FI"},
		{desc: "France", value: "fr-FR"},
		{desc: "Germany", value: "de-DE"},
		{desc: "Greece", value: "el-GR"},
		{desc: "Guatemala", value: "es-GT"},
		{desc: "Honduras", value: "es-HN"},
		{desc: "Hong Kong SAR (Trad.)", value: "cmn-Hans-HK"},
		{desc: "Hong Kong", value: "yue-Hant-HK"},
		{desc: "Hungary", value: "hu-HU"},
		{desc: "Iceland", value: "is-IS"},
		{desc: "India", value: "en-IN"},
		{desc: "India", value: "hi-IN"},
		{desc: "Indonesia", value: "id-ID"},
		{desc: "Iran", value: "fa-IR"},
		{desc: "Iraq", value: "ar-IQ"},
		{desc: "Ireland", value: "en-IE"},
		{desc: "Israel", value: "he-IL"},
		{desc: "Israel", value: "ar-IL"},
		{desc: "Italy", value: "it-IT"},
		{desc: "Japan", value: "ja-JP"},
		{desc: "Jordan", value: "ar-JO"},
		{desc: "Korea", value: "ko-KR"},
		{desc: "Kuwait", value: "ar-KW"},
		{desc: "Lebanon", value: "ar-LB"},
		{desc: "Lithuania", value: "lt-LT"},
		{desc: "Malaysia", value: "ms-MY"},
		{desc: "Morocco", value: "ar-MA"},
		{desc: "México", value: "es-MX"},
		{desc: "Netherlands", value: "nl-NL"},
		{desc: "New Zealand", value: "en-NZ"},
		{desc: "Nicaragua", value: "es-NI"},
		{desc: "Norway", value: "nb-NO"},
		{desc: "Oman", value: "ar-OM"},
		{desc: "Palestinian Territory", value: "ar-PS"},
		{desc: "Panamá", value: "es-PA"},
		{desc: "Paraguay", value: "es-PY"},
		{desc: "Perú", value: "es-PE"},
		{desc: "Philippines", value: "en-PH"},
		{desc: "Philippines", value: "fil-PH"},
		{desc: "Poland", value: "pl-PL"},
		{desc: "Portugal", value: "pt-PT"},
		{desc: "Puerto Rico", value: "es-PR"},
		{desc: "Qatar", value: "ar-QA"},
		{desc: "Romania", value: "ro-RO"},
		{desc: "Russia", value: "ru-RU"},
		{desc: "Saudi Arabia", value: "ar-SA"},
		{desc: "Serbia", value: "sr-RS"},
		{desc: "Slovakia", value: "sk-SK"},
		{desc: "Slovenia", value: "sl-SI"},
		{desc: "South Africa", value: "en-ZA"},
		{desc: "Spain", value: "es-ES"},
		{desc: "Sweden", value: "sv-SE"},
		{desc: "Switzerland", value: "it-CH"},
		{desc: "Taiwan (Trad.)", value: "cmn-Hant-TW"},
		{desc: "Thailand", value: "th-TH"},
		{desc: "Tunisia", value: "ar-TN"},
		{desc: "Turkey", value: "tr-TR"},
		{desc: "UAE", value: "ar-AE"},
		{desc: "Ukraine", value: "uk-UA"},
		{desc: "United Kingdom", value: "en-GB"},
		{desc: "United States", value: "en-US"},
		{desc: "Uruguay", value: "es-UY"},
		{desc: "Venezuela", value: "es-VE"},
		{desc: "Viet Nam", value: "vi-VN"}
    ]},
]);

cas_companion.options.addTab('Companion', [
    { name: 'cas_enable_active_call', desc: 'Enables CAS Companion', 'default': true},
    { name: 'cas_use_active_call_control', desc: 'Use ACS Call Control' },
    { name: 'cas_enable_shared_active_call_notification', desc: 'Enable Shared Call Notification' },
    { name: 'cas_enable_voice_transcription', desc: 'Enable Voice Transcription' },
    { type: 'h3', desc: 'Keywords ' },    
	{ type: 'list', name: 'cas_active_call_action_keywords', desc: 'List of Action Keywords. For example: next week follow up call me next step',
        head: false, sortable: true, fields: [{ type: 'text'}]
    },
    { type: 'h3', desc: 'Microsoft 365' }, 	
    { name: 'cas_active_call_group_id', 'default': 'fam', type: 'text', desc: 'Collaboration Group Id', singleline: true },
    { name: 'cas_active_call_thread_id', 'default': 'fam', type: 'text', desc: 'Collaboration Thread Id', singleline: true },
    { name: 'cas_one_note_section_id', 'default': '1-34167a55-e4a4-4c4c-ac99-dec00153c31a', type: 'text', desc: 'OneNote Section Id', singleline: true },
    { name: 'cas_delegate_userid', 'default': 'ba9e081a-5748-40ca-8fd5-ab9c74dae3d1', type: 'text', desc: 'Delegate User Id', singleline: true },
    { name: 'cas_deep_link_id', 'default': 'eaf9ea54-1859-4b20-bafb-8cb665f1ef37', type: 'text', desc: 'Deep Link Id', singleline: true },
    { type: 'h3', desc: 'Intelliflo' },	
    { name: 'cas_enable_intelliflo', desc: 'Enable Workflow. Sync Intelliflo clients with Teams contacts. Popup will only happen when open workstation button is pressed'},	
    { name: 'cas_autopop_intelliflo', desc: 'Auto-popup Client Details. Navigate Intelliflo to the client dashboard page of the caller when call is active.'},	
    { name: 'cas_embed_in_workstation', desc: 'Embed in Client Workstation. When current call is connected, move active call window to an Intelliflo widget.'},	
	
]);